### ISSUE TITLE
Container Healthcheck is Failing in Docker Compose

### ISSUE THREAD

**Issue by SuperJC710e** [WasinUddy/Montainer#15]
Hi! Thanks for this project! Just testing it out in docker compose.

I noticed that the container always said it was unhealthy, so I investigated. It appears that there are two things that cause an issue, the first is that `localhost` fails to resolve properly, and the `--spider` option for `wget` fails. (Apparently that sends a `HEAD` request instead of a `GET` request, and the Minecraft server does not like it. Reference: [https://stackoverflow.com/questions/47722898/how-can-i-make-a-docker-healthcheck-with-wget-instead-of-curl](https://stackoverflow.com/questions/47722898/how-can-i-make-a-docker-healthcheck-with-wget-instead-of-curl)

In my `docker-compose.yml` file I was able to override it and get it working:

```yaml
...
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://0.0.0.0:8000/healthz || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
...
```

Result:

```bash
# docker inspect --format "{{json .State.Health }}" montainer | jq
{
  "Status": "healthy",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2025-01-21T04:17:07.531188015Z",
      "End": "2025-01-21T04:17:07.610053604Z",
      "ExitCode": 0,
      "Output": "{\"status\":\"ok\"}"
    }
  ]
}
```

I haven't tried with `docker run` directly, so I'm not sure if the current healthcheck only fails in `compose` or not.
